# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU


twilio_phone: '4156589140'
twilio_url: 'http://twimlets.com/echo?Twiml=%3CResponse%3E%3CSms%3EHello+Brian%2C+thanks+for+the+message%21%3C%2FSms%3E%3C%2FResponse%3E'
twilio_auth_token: 'b1f33b75e2110703774a83396b800a65'
twilio_sid: 'ACca1414fbd6f37f801d55d6e9ca911860'